# workflow to publish the docs projects to CF

name: publish-fe-orchestrator-docker-package

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths: 
      - 'client/**'
      - 'server/**'
      - 'Dockerfile'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: show files
        run: ls -la

      - name: Build image
        run: docker build . --file Dockerfile --tag ghcr.io/alexanderbartels/open-microfrontends:latest

      - name: Log into registry
        run: echo "${{ secrets.PERSONAL_GH_TOKEN }}" | docker login ghcr.io -u alexanderbartels --password-stdin

      - name: Build and push
        run: docker push ghcr.io/alexanderbartels/open-microfrontends:latest
